services:
  app:
    image: ghcr.io/meisterlala/laracasts:latest
    build: !reset null
    env_file: !override ".env"
    ports: !reset []
    expose:
      - 80
    volumes: !reset ""
  db:
    env_file: !override ".env"
  pgadmin: !reset ""

networks:
  default:
    name: proxy_host
    external: true
